spring:
  main:
    allow-circular-references: true
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datadump.location:
  authors: C:\Users\Michael\Desktop\authors.txt
  works: C:\Users\Michael\Desktop\works.txt

datastax.astra:
  secure-connect-bundle: secure-connect-hizencode-reads.zip

astra.db:
  id: <db-id>
  regioin: <region>
  keyspace: main
  application.token: <token>